export const questions = [
	`Who is most likely to win a hot dog eating contest?`,
	`‍Who is most likely to forget to pick up their kids from school?`,
	`‍Who is most likely to keep a check on their children’s social media accounts?`,
	`‍Who is most likely to get hungry in the middle of the night?`,
	`‍Who is most likely to remain asleep while the alarm is blaring?`,
	`‍Who is most likely to give their kid a pretty terrible name?`,
	`‍Who is most likely to spend hours on a celebrity conspiracy theory?`,
	`‍Who is most likely to go a week without a shower?`,
	`‍Who is most likely to replace salt with sugar while cooking?`,
	`‍Who is most likely to snooze their alarm indefinitely in the mornings?`,
	`‍Who is most likely to sleep while brushing their teeth?`,
	`‍Who is most likely to talk while dreaming?`,
	`‍Who is most likely to snore while sleeping?`,
	`‍Who is most likely to be the most scared while watching a horror movie?`,
	`‍Who is most likely to join a street gang?`,
	`‍Who is most likely to be popular at school?`,
	`‍Who is the most likely to spread gossip?`,
	`‍Who is most likely to cheat on a test and get caught?`,
	`‍Who is most likely to be in the middle of drama?`,
	`‍Who is most likely to be on the news for scam?`,
	`‍Who is most likely to forget where they parked their car?`,
	`‍Who is most likely to get Hangry (Hungry + angry)?`,
	`‍Who is most likely to call the restaurant manager to complain during a meal?`,
	`‍Who is most likely to forget their car keys inside their car?`,
	`‍Who is most likely to click on a spam ad pop-up on the internet?`,
	`‍Who is most likely to get drunk after one drink?`,
	`‍Who is most likely to tell a joke that gets them into trouble?`,
	`‍Who is most likely to fart in an elevator full of people?`,
	`‍Who is most likely to stay up all night scrolling on their phone?`,
	`‍Who is most likely to disappear for a year?`,
	`Who is most likely to say something inappropriate during a meeting?`,
	`‍Who is most likely to take the day off after partying the previous night?`,
	`‍Who is most likely to show up at work drunk?`,
	`‍Who is most likely to be a team player at work?`,
	`‍Who is most likely to call their manager “mom or dad”?`,
	`‍Who is most likely to have a side hustle?`,
	`‍Who is most likely to be nail a presentation?`,
	`‍Who is most likely to ignore a social media request from a coworker?`,
	`‍Who is most likely to get praised at work?`,
	`‍Who is most likely to get drunk at an office retreat?`,
	`‍Who is most likely to have the best Zoom background?`,
	`‍Who is most likely to win during virtual trivia nights?`,
	`‍Who is most likely to keep talking with their mic off during a virtual meeting?`,
	`‍Who is most likely to lie at a job interview?`,
	`‍Who is most likely to have the most unread work emails?`,
	`‍Who is most likely to be the office gossip?`,
	`‍Who is most likely to take the most sick days?`,
	`‍Who is most likely to fall asleep during a meeting?`,
	`‍Who is most likely to come to work in pajamas?`,
	`‍Who is most likely to work from home in their bed?`,
	`‍Who is most likely to have the biggest snack drawer?`,
	`‍Who is most likely to make everyone laugh during a meeting?`,
	`‍Who is most likely to plan a team outing?`,
	`‍Who is most likely to get a computer virus?`,
	`‍Who is most likely to save their work only to lose it all?`,
	`‍Who is most likely to make friends with everyone at work?`,
	`‍Who is most likely to be the CEO one day?`,
	`‍Who is most likely to forget to turn off the mic during a Zoom call?`,
	`‍Who is most likely to reply to Slack messages with GIFs?`,
	`‍Who is most likely to accidentally send “I love you” to a client?`,
	`Who is most likely to have gotten suspended from school?`,
	`‍Who is most likely to get into a bar fight?`,
	`‍Who is most likely to forget to flush the toilet?`,
	`‍Who is most likely to eat something off the floor?`,
	`‍Who is most likely to take a ride from a stranger?`,
	`‍Who is most likely to get into an argument with a little kid?`,
	`‍Who is most likely to eat food that doesn’t belong to them?`,
	`‍Who is most likely to get into a fight on the internet?`,
	`‍Who is most likely to eat pop tarts for breakfast?`,
	`‍Who is most likely to pick their nose when they think nobody is watching?`,
	`‍Who is most likely to crack dirty jokes and make everyone uncomfortable?`,
	`‍Who is most likely to be drinking at 3:00 pm?`,
	`‍Who is most likely to snack late at night?`,
	`‍Who is most likely to eat weird food combinations?`,
	`‍Who is most likely to lick their plate after a meal?`,
	`‍Who is most likely to burp in a crowd?`,
	`Who is most likely to try eating cat food?`,
	`‍Who is most likely to forget wearing underwear?`,
	`‍Who is most likely to eat something alive?`,
	`‍Who is most likely to kiss a frog?`,
	`‍Who is most likely to try the weird things in public?`,
	`‍Who is most likely not to take a bath for days?`,
	`‍Who is most likely to get arrested for a dare in public?`,
	`‍Who is most likely to be hungover at a church service?`,
	`‍Who is most likely to get kicked out of a theater?`,
	`‍Who is most likely to swear in front of a kid?`,
	`‍Who is most likely to have the most parking tickets?`,
	`‍Who is most likely to stalk their favorite celebrity?`,
	`‍Who is most likely to eat something gross?`,
	`‍Who is most likely to laugh during a serious moment?`,
	`Who is most likely to forget to text back?`,
	`‍Who is most likely to embarrass you in front of your parents?`,
	`‍Who is most likely to make you laugh when you are sad?`,
	`‍Who is most likely to pick up your calls in the middle of the night?`,
	`‍Who is most likely to send memes and GIFs to you everyday?`,
	`‍Who is most likely to bake you a birthday cake?`,
	`‍Who is most likely to cancel on their friends without a proper reason?`,
	`‍Who is most likely to do TikTok dance videos with you?`,
	`‍Who is most likely to keep a friend’s secret?`,
	`‍Who is most likely to tell the most lame jokes?`,
	`‍Who is most likely to be the best liar?`,
	`‍Who is most likely to give you a nickname?`,
	`‍Who is most likely to be asked for ID at age 35?`,
	`Who is most likely to forget your birthday?`,
	`‍Who is most likely to text back immediately?`,
	`‍Who is most likely to be a cool parent?`,
	`‍Who is most likely to spend all their money on clothes?`,
	`‍Who is most likely to save you from a bad date?`,
	`‍Who is most likely to tell you to leave a bad relationship behind?`,
	`‍Who is most likely to have the best snacks?`,
	`‍Who is most likely to have the best dance moves at a party?`,
	`‍Who is most likely to be an awesome DJ?`,
	`‍Who is most likely to get caught texting their ex?`,
	`‍Who is most likely to sing in the shower?`,
	`‍Who is most likely to travel with you to Europe?`,
	`‍Who is most likely to move in with you?`,
	`‍Who is most likely to cook your favorite meals for you?`,
	`‍Who is most likely to get you the best birthday gift?`,
	`‍Who is most likely to treat your house like it’ their house?`,
	`‍Who is most likely to get along better with your parents?`,
	`Who is most likely to take the entire blanket while sleeping?`,
	`‍Who is most likely to crush on a celebrity?`,
	`‍Who is most likely to end up doing household chores?`,
	`‍Who is most likely to get food stuck in their teeth?`,
	`‍Who is most likely to get cranky when hungry?`,
	`‍Who is most likely to be a trip planner?`,
	`‍Who is most likely to be the one who saves money?`,
	`‍Who is most likely to plan the future?`,
	`‍Who is most likely to be the messy one?`,
	`‍Who’s most likely to binge-watch an entire show in a day?`,
	`‍Who is most likely to forget to buy the groceries?`,
	`‍Who is most likely to spend money on expensive snacks?`,
	`‍Who is most likely to eat all the popcorn while watching a movie?`,
	`‍Who is most likely to talk in the movie theater during a movie?`,
	`‍Who is most likely to forget their keys at home?`,
	`‍Who is most likely to take longer to get ready in the morning?`,
	`‍Who is most likely to be more patient?`,
	`‍Who is most likely to be more romantic?`,
	`‍Who is most likely to take the entire bed while sleeping?`,
	`‍Who is most likely to be the funny one?`,
	`‍Who is most likely to be flirty?`,
	`‍Who is most likely to plan an expensive dinner date?`,
	`‍Who is most likely to spend their money on something stupid?`,
	`‍Who is most likely to remain calm during a storm?`,
	`‍Who is most likely to forget to do the dishes?`,
	`‍Who is most likely to be a stingy parent?`,
	`‍Who is most likely to drop their new phone?`,
	`‍Who is more likely to enjoy living alone in the wilderness?`,
	`‍Who’s most likely to scream at a spider?`,
	`‍Who is most likely to watch a horror movie by themselves at night?`,
	`Who is most likely to remind the teacher about homework?`,
	`‍Who is most likely to fall asleep in class?`,
	`‍Who is most likely to fall down during P.E.?`,
	`‍Who is most likely to lose their stationery?`,
	`‍Who is most likely to do voices when reading out loud?`,
	`‍Who is most likely to become a poet?`,
	`‍Who is most likely to be a teacher’s pet?`,
	`‍Who is most likely to cut their hair themselves?`,
	`‍Who is most likely to play in mud during recess?`,
	`‍Who is most likely to drop their lunch?`,
	`‍Who is most likely to be a Math genius?`,
	`‍Who is most likely to have a messy desk or locker?`,
	`‍Who is most likely to mimic their teacher in class?`,
	`‍Who is most likely to get in trouble?`,
	`‍Who is most likely to borrow a pencil and never return it?`,
	`‍Who is most likely to win a writing contest?`,
	`‍Who is most likely to fake being sick to avoid school?`,
	`‍Who is most likely to make a friendship bracelet?`,
	`‍Who is most likely to sneak in their pet to class?`,
	`‍Who is most likely to get into an argument at school?`,
	`‍Who is most likely to be the most popular kid?`,
	`‍Who is most likely to have the best lunch?`,
	`‍Who is most likely to grow up to be a chef?`,
	`‍Who is most likely to come late to class?`,
	`‍Who is most likely to get locked in the toilet?`,
	`‍Who is most likely to have the most colorful locker?`,
	`‍Who is most likely to never do their homework?`,
	`‍Who is most likely to forget their lunch at home?`,
	`‍Who is most likely to win the talent show?`,
	`‍Who is most likely to have an awkward yearbook photo?`
];
export const randomQuestion = () => questions[Math.floor(Math.random() * questions.length)];
